/** ###################################################################
**     THIS COMPONENT MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename    : task_template_list.c
**     Project     : ProcessorExpert
**     Processor   : MK20DX128VLH5
**     Version     : Component 01.106, Driver 01.00, CPU db: 3.00.000
**     Compiler    : GNU C Compiler
**     Date/Time   : 2013-10-01, 05:33, # CodeGen: 0
**
**     Copyright : 1997 - 2013 Freescale Semiconductor, Inc. All Rights Reserved.
**     SOURCE DISTRIBUTION PERMISSIBLE as directed in End User License Agreement.
**     
**     http      : www.freescale.com
**     mail      : support@freescale.com
** ###################################################################*/
/*!
** @file task_template_list.c                                                  
** @version 01.00
*/         
/*!
**  @addtogroup task_template_list_module task_template_list module documentation
**  @{
*/         

#include "task_template_list.h"
#include "mqx_tasks.h"

#define TASK_TEMPLATE_LIST_END         {0, 0, 0, 0, 0, 0, 0}

/* MQX task template list */
const TASK_TEMPLATE_STRUCT MQX_template_list[] =
{
  /* Task: Task1 */
  {
  /* Task number                      */  TASK1_TASK,
  /* Entry point                      */  (TASK_FPTR)Task1_task,
  /* Stack size                       */  TASK1_TASK_STACK_SIZE,
  /* Task priority                    */  8U,
  /* Task name                        */  "task1",
  /* Task attributes                  */  (MQX_AUTO_START_TASK),
  /* Task parameter                   */  (uint32_t)(0)
  },
  TASK_TEMPLATE_LIST_END
};

/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.3 [05.08]
**     for the Freescale Kinetis series of microcontrollers.
**
** ###################################################################
*/
